In [111]:
import pandas as pd
import numpy as np

In [112]:
df = pd.read_csv('bank-additional-full.csv',sep = ';')

In [113]:
df.head()

age        job  marital    education  default housing loan    contact  \
0   56  housemaid  married     basic.4y       no      no   no  telephone   
1   57   services  married  high.school  unknown      no   no  telephone   
2   37   services  married  high.school       no     yes   no  telephone   
3   40     admin.  married     basic.6y       no      no   no  telephone   
4   56   services  married  high.school       no      no  yes  telephone   

  month day_of_week  ...  campaign  pdays  previous     poutcome emp.var.rate  \
0   may         mon  ...         1    999         0  nonexistent          1.1   
1   may         mon  ...         1    999         0  nonexistent          1.1   
2   may         mon  ...         1    999         0  nonexistent          1.1   
3   may         mon  ...         1    999         0  nonexistent          1.1   
4   may         mon  ...         1    999         0  nonexistent          1.1   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed   y  
0          93.994          -36.4      4.857       5191.0  no  
1          93.994          -36.4      4.857       5191.0  no  
2          93.994          -36.4      4.857       5191.0  no  
3          93.994          -36.4      4.857       5191.0  no  
4          93.994          -36.4      4.857       5191.0  no  

[5 rows x 21 columns]

In [114]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             41188 non-null  int64  
 1   job             41188 non-null  object 
 2   marital         41188 non-null  object 
 3   education       41188 non-null  object 
 4   default         41188 non-null  object 
 5   housing         41188 non-null  object 
 6   loan            41188 non-null  object 
 7   contact         41188 non-null  object 
 8   month           41188 non-null  object 
 9   day_of_week     41188 non-null  object 
 10  duration        41188 non-null  int64  
 11  campaign        41188 non-null  int64  
 12  pdays           41188 non-null  int64  
 13  previous        41188 non-null  int64  
 14  poutcome        41188 non-null  object 
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null 

In [115]:
df.isnull().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
dtype: int64

In [116]:
df.dtypes

age                 int64
job                object
marital            object
education          object
default            object
housing            object
loan               object
contact            object
month              object
day_of_week        object
duration            int64
campaign            int64
pdays               int64
previous            int64
poutcome           object
emp.var.rate      float64
cons.price.idx    float64
cons.conf.idx     float64
euribor3m         float64
nr.employed       float64
y                  object
dtype: object

In [117]:
cat_feat  = df.dtypes[df.dtypes == object].index

In [118]:
cat_feat

Index(['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact',
       'month', 'day_of_week', 'poutcome', 'y'],
      dtype='object')

In [119]:
cat_feat = cat_feat.drop('y')

In [120]:
cat_feat

Index(['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact',
       'month', 'day_of_week', 'poutcome'],
      dtype='object')

In [121]:
cat_feat = cat_feat.drop('month')

In [122]:
cat_feat = cat_feat.drop('day_of_week')

In [123]:
cat_feat

Index(['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact',
       'poutcome'],
      dtype='object')

In [124]:
for i in cat_feat:
    print(df[i].unique())

['housemaid' 'services' 'admin.' 'blue-collar' 'technician' 'retired'
 'management' 'unemployed' 'self-employed' 'unknown' 'entrepreneur'
 'student']
['married' 'single' 'divorced' 'unknown']
['basic.4y' 'high.school' 'basic.6y' 'basic.9y' 'professional.course'
 'unknown' 'university.degree' 'illiterate']
['no' 'unknown' 'yes']
['no' 'yes' 'unknown']
['no' 'yes' 'unknown']
['telephone' 'cellular']
['nonexistent' 'failure' 'success']


In [125]:
df_jobs = pd.get_dummies(df['job']).drop(columns = 'unknown')

In [126]:
df.drop(columns = 'job',inplace = True)

In [127]:
df = df.join(df_jobs)

In [128]:
df.head()

age  marital    education  default housing loan    contact month  \
0   56  married     basic.4y       no      no   no  telephone   may   
1   57  married  high.school  unknown      no   no  telephone   may   
2   37  married  high.school       no     yes   no  telephone   may   
3   40  married     basic.6y       no      no   no  telephone   may   
4   56  married  high.school       no      no  yes  telephone   may   

  day_of_week  duration  ...  blue-collar  entrepreneur  housemaid management  \
0         mon       261  ...            0             0          1          0   
1         mon       149  ...            0             0          0          0   
2         mon       226  ...            0             0          0          0   
3         mon       151  ...            0             0          0          0   
4         mon       307  ...            0             0          0          0   

   retired  self-employed  services  student  technician unemployed  
0        0              0         0        0           0          0  
1        0              0         1        0           0          0  
2        0              0         1        0           0          0  
3        0              0         0        0           0          0  
4        0              0         1        0           0          0  

[5 rows x 31 columns]

In [129]:
df_married = pd.get_dummies(df['marital'])

In [130]:
df.drop(columns = 'marital',inplace = True)

In [131]:
df.head()

age    education  default housing loan    contact month day_of_week  \
0   56     basic.4y       no      no   no  telephone   may         mon   
1   57  high.school  unknown      no   no  telephone   may         mon   
2   37  high.school       no     yes   no  telephone   may         mon   
3   40     basic.6y       no      no   no  telephone   may         mon   
4   56  high.school       no      no  yes  telephone   may         mon   

   duration  campaign  ...  blue-collar  entrepreneur housemaid  management  \
0       261         1  ...            0             0         1           0   
1       149         1  ...            0             0         0           0   
2       226         1  ...            0             0         0           0   
3       151         1  ...            0             0         0           0   
4       307         1  ...            0             0         0           0   

   retired  self-employed  services  student technician  unemployed  
0        0              0         0        0          0           0  
1        0              0         1        0          0           0  
2        0              0         1        0          0           0  
3        0              0         0        0          0           0  
4        0              0         1        0          0           0  

[5 rows x 30 columns]

In [132]:
df = df.join(df_married)

In [133]:
df.head()

age    education  default housing loan    contact month day_of_week  \
0   56     basic.4y       no      no   no  telephone   may         mon   
1   57  high.school  unknown      no   no  telephone   may         mon   
2   37  high.school       no     yes   no  telephone   may         mon   
3   40     basic.6y       no      no   no  telephone   may         mon   
4   56  high.school       no      no  yes  telephone   may         mon   

   duration  campaign  ...  retired  self-employed services  student  \
0       261         1  ...        0              0        0        0   
1       149         1  ...        0              0        1        0   
2       226         1  ...        0              0        1        0   
3       151         1  ...        0              0        0        0   
4       307         1  ...        0              0        1        0   

   technician  unemployed  divorced  married single  unknown  
0           0           0         0        1      0        0  
1           0           0         0        1      0        0  
2           0           0         0        1      0        0  
3           0           0         0        1      0        0  
4           0           0         0        1      0        0  

[5 rows x 34 columns]

In [134]:
df.drop(columns = 'unknown',inplace = True)

In [135]:
df.head()
len(df.columns)
df.shape

(41188, 33)

In [136]:
cat_feat = cat_feat.delete([0])

In [137]:
cat_feat = cat_feat.delete([0])

In [138]:
cat_feat = cat_feat.delete([0])

In [140]:
df_education = pd.get_dummies(df['education'])

In [142]:
df_education.drop(columns = 'unknown',inplace = True)

In [144]:
df = df.join(df_education)

In [146]:
df.drop(columns = 'education',inplace = True)

In [147]:
len(df.columns)

39

In [148]:
df_def = pd.get_dummies(df['default'])

In [149]:
df_def.drop(columns = 'unknown',inplace = True)

In [150]:
df.drop(columns = 'default',inplace = True)

In [151]:
df = df.join(df_def)

In [152]:
len(df.columns)

40

In [153]:
df.head()

age housing loan    contact month day_of_week  duration  campaign  pdays  \
0   56      no   no  telephone   may         mon       261         1    999   
1   57      no   no  telephone   may         mon       149         1    999   
2   37     yes   no  telephone   may         mon       226         1    999   
3   40      no   no  telephone   may         mon       151         1    999   
4   56      no  yes  telephone   may         mon       307         1    999   

   previous  ... single  basic.4y  basic.6y  basic.9y  high.school  \
0         0  ...      0         1         0         0            0   
1         0  ...      0         0         0         0            1   
2         0  ...      0         0         0         0            1   
3         0  ...      0         0         1         0            0   
4         0  ...      0         0         0         0            1   

   illiterate professional.course  university.degree  no  yes  
0           0                   0                  0   1    0  
1           0                   0                  0   0    0  
2           0                   0                  0   1    0  
3           0                   0                  0   1    0  
4           0                   0                  0   1    0  

[5 rows x 40 columns]

In [154]:
df_loan = pd.get_dummies(df['loan'])

In [156]:
df_loan.drop(columns = 'unknown',inplace = True)

In [157]:
df.drop(columns = 'loan',inplace = True)

In [158]:
df = df.join(df_loan,rsuffix = '_loan')

In [159]:
df.head()

age housing    contact month day_of_week  duration  campaign  pdays  \
0   56      no  telephone   may         mon       261         1    999   
1   57      no  telephone   may         mon       149         1    999   
2   37     yes  telephone   may         mon       226         1    999   
3   40      no  telephone   may         mon       151         1    999   
4   56      no  telephone   may         mon       307         1    999   

   previous     poutcome  ...  basic.6y  basic.9y  high.school  illiterate  \
0         0  nonexistent  ...         0         0            0           0   
1         0  nonexistent  ...         0         0            1           0   
2         0  nonexistent  ...         0         0            1           0   
3         0  nonexistent  ...         1         0            0           0   
4         0  nonexistent  ...         0         0            1           0   

   professional.course university.degree  no  yes  no_loan  yes_loan  
0                    0                 0   1    0        1         0  
1                    0                 0   0    0        1         0  
2                    0                 0   1    0        1         0  
3                    0                 0   1    0        1         0  
4                    0                 0   1    0        0         1  

[5 rows x 41 columns]

In [160]:
len(df.columns)

41

In [161]:
df_housing = pd.get_dummies(df['housing'])

In [162]:
df_housing

no  unknown  yes
0       1        0    0
1       1        0    0
2       0        0    1
3       1        0    0
4       1        0    0
...    ..      ...  ...
41183   0        0    1
41184   1        0    0
41185   0        0    1
41186   1        0    0
41187   0        0    1

[41188 rows x 3 columns]

In [163]:
df_housing.drop(columns = 'unknown',inplace = True)

In [164]:
df.drop(columns = 'housing',inplace = True)

In [165]:
df = df.join(df_housing,rsuffix = '_housing')

In [166]:
df.head()

age    contact month day_of_week  duration  campaign  pdays  previous  \
0   56  telephone   may         mon       261         1    999         0   
1   57  telephone   may         mon       149         1    999         0   
2   37  telephone   may         mon       226         1    999         0   
3   40  telephone   may         mon       151         1    999         0   
4   56  telephone   may         mon       307         1    999         0   

      poutcome  emp.var.rate  ...  high.school  illiterate  \
0  nonexistent           1.1  ...            0           0   
1  nonexistent           1.1  ...            1           0   
2  nonexistent           1.1  ...            1           0   
3  nonexistent           1.1  ...            0           0   
4  nonexistent           1.1  ...            1           0   

   professional.course  university.degree no  yes  no_loan  yes_loan  \
0                    0                  0  1    0        1         0   
1                    0                  0  0    0        1         0   
2                    0                  0  1    0        1         0   
3                    0                  0  1    0        1         0   
4                    0                  0  1    0        0         1   

   no_housing  yes_housing  
0           1            0  
1           1            0  
2           0            1  
3           1            0  
4           1            0  

[5 rows x 42 columns]

In [167]:
cat_feat

Index(['default', 'housing', 'loan', 'contact', 'poutcome'], dtype='object')

In [168]:
df_cont = pd.get_dummies(df['contact'])

In [170]:
df_cont.drop(columns = 'telephone',inplace = True)

In [171]:
df.drop(columns = 'contact',inplace = True)

In [172]:
df = df.join(df_cont)

In [173]:
df.head()

age month day_of_week  duration  campaign  pdays  previous     poutcome  \
0   56   may         mon       261         1    999         0  nonexistent   
1   57   may         mon       149         1    999         0  nonexistent   
2   37   may         mon       226         1    999         0  nonexistent   
3   40   may         mon       151         1    999         0  nonexistent   
4   56   may         mon       307         1    999         0  nonexistent   

   emp.var.rate  cons.price.idx  ...  illiterate  professional.course  \
0           1.1          93.994  ...           0                    0   
1           1.1          93.994  ...           0                    0   
2           1.1          93.994  ...           0                    0   
3           1.1          93.994  ...           0                    0   
4           1.1          93.994  ...           0                    0   

   university.degree no  yes  no_loan  yes_loan  no_housing  yes_housing  \
0                  0  1    0        1         0           1            0   
1                  0  0    0        1         0           1            0   
2                  0  1    0        1         0           0            1   
3                  0  1    0        1         0           1            0   
4                  0  1    0        0         1           1            0   

   cellular  
0         0  
1         0  
2         0  
3         0  
4         0  

[5 rows x 42 columns]

In [174]:
cat_feat

Index(['default', 'housing', 'loan', 'contact', 'poutcome'], dtype='object')

In [175]:
df_p = pd.get_dummies(df['poutcome'])

In [177]:
df_p.drop(columns = 'failure',inplace = True)

In [178]:
df.drop(columns = 'poutcome',inplace =  True)

In [179]:
df = df.join(df_p)

In [180]:
df.head()

age month day_of_week  duration  campaign  pdays  previous  emp.var.rate  \
0   56   may         mon       261         1    999         0           1.1   
1   57   may         mon       149         1    999         0           1.1   
2   37   may         mon       226         1    999         0           1.1   
3   40   may         mon       151         1    999         0           1.1   
4   56   may         mon       307         1    999         0           1.1   

   cons.price.idx  cons.conf.idx  ...  university.degree  no yes  no_loan  \
0          93.994          -36.4  ...                  0   1   0        1   
1          93.994          -36.4  ...                  0   0   0        1   
2          93.994          -36.4  ...                  0   1   0        1   
3          93.994          -36.4  ...                  0   1   0        1   
4          93.994          -36.4  ...                  0   1   0        0   

   yes_loan  no_housing  yes_housing  cellular  nonexistent  success  
0         0           1            0         0            1        0  
1         0           1            0         0            1        0  
2         0           0            1         0            1        0  
3         0           1            0         0            1        0  
4         1           1            0         0            1        0  

[5 rows x 43 columns]

In [182]:
df.drop(columns = ['month','day_of_week','duration'],inplace = True)

In [183]:
df.columns

Index(['age', 'campaign', 'pdays', 'previous', 'emp.var.rate',
       'cons.price.idx', 'cons.conf.idx', 'euribor3m', 'nr.employed', 'y',
       'admin.', 'blue-collar', 'entrepreneur', 'housemaid', 'management',
       'retired', 'self-employed', 'services', 'student', 'technician',
       'unemployed', 'divorced', 'married', 'single', 'basic.4y', 'basic.6y',
       'basic.9y', 'high.school', 'illiterate', 'professional.course',
       'university.degree', 'no', 'yes', 'no_loan', 'yes_loan', 'no_housing',
       'yes_housing', 'cellular', 'nonexistent', 'success'],
      dtype='object')

In [185]:
df['pdays'].unique()

array([999,   6,   4,   3,   5,   1,   0,  10,   7,   8,   9,  11,   2,
        12,  13,  14,  15,  16,  21,  17,  18,  22,  25,  26,  19,  27,
        20], dtype=int64)

In [186]:
df.dtypes

age                      int64
campaign                 int64
pdays                    int64
previous                 int64
emp.var.rate           float64
cons.price.idx         float64
cons.conf.idx          float64
euribor3m              float64
nr.employed            float64
y                       object
admin.                   uint8
blue-collar              uint8
entrepreneur             uint8
housemaid                uint8
management               uint8
retired                  uint8
self-employed            uint8
services                 uint8
student                  uint8
technician               uint8
unemployed               uint8
divorced                 uint8
married                  uint8
single                   uint8
basic.4y                 uint8
basic.6y                 uint8
basic.9y                 uint8
high.school              uint8
illiterate               uint8
professional.course      uint8
university.degree        uint8
no                       uint8
yes     

In [187]:
df['cons.price.idx'].describe()

count    41188.000000
mean        93.575664
std          0.578840
min         92.201000
25%         93.075000
50%         93.749000
75%         93.994000
max         94.767000
Name: cons.price.idx, dtype: float64

In [189]:
df['emp.var.rate'].describe()

count    41188.000000
mean         0.081886
std          1.570960
min         -3.400000
25%         -1.800000
50%          1.100000
75%          1.400000
max          1.400000
Name: emp.var.rate, dtype: float64

In [191]:
df['cons.conf.idx'].describe()

count    41188.000000
mean       -40.502600
std          4.628198
min        -50.800000
25%        -42.700000
50%        -41.800000
75%        -36.400000
max        -26.900000
Name: cons.conf.idx, dtype: float64

In [193]:
from sklearn.preprocessing import LabelEncoder

In [194]:
le_y = LabelEncoder()
df['y'] = le_y.fit_transform(df['y'])

In [195]:
df['y']

0        0
1        0
2        0
3        0
4        0
        ..
41183    1
41184    0
41185    0
41186    1
41187    0
Name: y, Length: 41188, dtype: int32

In [196]:
y = df['y'].values

In [197]:
df.drop(columns = 'y',inplace = True)

In [202]:
X = df.values

In [203]:
from sklearn.model_selection import train_test_split

In [204]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 0)

In [215]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)
X_train1 = X_train
X_test1  = X_test
y_train1 = y_train
y_test1 = y_test

(32950, 39)
(8238, 39)
(32950,)
(8238,)


In [206]:
from sklearn.preprocessing import StandardScaler

In [207]:
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [208]:
from sklearn.ensemble import RandomForestClassifier

In [209]:
classifier = RandomForestClassifier(n_estimators = 100,criterion = 'entropy',random_state = 0)

In [210]:
classifier.fit(X_train,y_train)
y_pred = classifier.predict(X_test)

In [211]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[7102,  217],
       [ 644,  275]], dtype=int64)

In [212]:
from sklearn.model_selection import cross_val_score

In [213]:
accuracy_vector = cross_val_score(estimator = classifier,X = X_train,y = y_train,cv = 10,n_jobs = -1)
print(accuracy_vector)
print(accuracy_vector.mean())
print(accuracy_vector.std())

[0.89377845 0.89468892 0.88437026 0.8952959  0.89802731 0.88801214
 0.89044006 0.89468892 0.89772382 0.89468892]
0.8931714719271623
0.004094305785502911


In [214]:
from xgboost import XGBClassifier

In [218]:
classifier1 = XGBClassifier()
classifier1.fit(X_train1,y_train1)
y_predx = classifier1.predict(X_test1)

In [219]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test1,y_predx)
cm

array([[7214,  105],
       [ 714,  205]], dtype=int64)

In [220]:
accuracy_vectorx = cross_val_score(estimator = classifier1,X = X_train1,y = y_train1,cv = 10,n_jobs = -1)
print(accuracy_vectorx)
print(accuracy_vectorx.mean())
print(accuracy_vectorx.std())

[0.89742033 0.89954476 0.89195751 0.90409712 0.90440061 0.89863429
 0.89742033 0.90197269 0.89954476 0.90197269]
0.8996965098634293
0.003511185455364537


In [221]:
from sklearn.naive_bayes import GaussianNB

In [222]:
classifier2 = GaussianNB()
classifier2.fit(X_train,y_train)
y_pred2 = classifier2.predict(X_test)

In [223]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred2)
cm

array([[3626, 3693],
       [ 170,  749]], dtype=int64)

In [224]:
from sklearn.linear_model import LogisticRegression

In [225]:
classifier3 = LogisticRegression(random_state = 0)
classifier3.fit(X_train,y_train)
y_predlr = classifier3.predict(X_test)

In [226]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_predlr)
cm

array([[7209,  110],
       [ 715,  204]], dtype=int64)

In [227]:
accuracy_vectorlr = cross_val_score(estimator = classifier3,X = X_train1,y = y_train1,cv = 10,n_jobs = -1)
print(accuracy_vectorlr)
print(accuracy_vectorlr.mean())
print(accuracy_vectorlr.std())

[0.8983308  0.89590288 0.89620637 0.90106222 0.90257967 0.89954476
 0.89590288 0.90227618 0.9016692  0.90106222]
0.899453717754173
0.0025466059721757986


In [1]:
7209+204

7413

In [2]:
715+110

825

In [3]:
7413/(825+7413)

0.8998543335761107